version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    networks:
      - my_network

  python_script:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pythonscript
    depends_on:
      - mongodb
    networks:
      - my_network

networks:
  my_network:
